url: https://wampastomper.com
collections:
  portfolio:
    output: true
    permalink: /pages/gallery/:title/

defaults:
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      nav-color: "nbar-light"