---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: documents
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _portfolio
  label: Portfolio
  create: all
  match: "**/*"
  templates:
  - gallery
upload_dir: docs/assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":month:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d docs
  publish_command: bundle exec jekyll build --destination docs
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: "/docs"
  output_directory: /docs
