---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _portfolio
  label: Portfolio
  create: all
  match: "**/*"
upload_dir: docs/assets/gallery
public_path: "/assets/gallery"
front_matter_path: ''
use_front_matter_path: false
file_template: ":image_folder:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: "/docs"
  output_directory: _site
